---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: echo-server
  name: echo-server
spec:
  ports:
    - name: service
      port: 1323
      protocol: TCP
      targetPort: service
  selector:
    app.kubernetes.io/name: echo-server