name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

#      - name: Build
#        run: go build -v ./...

      - name: Install dependencies
        run: make vendor-update

      - name: Run build
        run: make package

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: echo-server-prod
          path: bin/echo-server-prod